# Test your FastAPI endpoints

GET http://127.0.0.1:8000/blue
Content-Type: application/json

###

GET http://127.0.0.1:8000/oficial
Content-Type: application/json

###

GET http://127.0.0.1:8000/mep
Content-Type: application/json

###

GET http://127.0.0.1:8000/ccl
Content-Type: application/json

###

GET http://127.0.0.1:8000/mayorista
Content-Type: application/json

###

GET http://127.0.0.1:8000/cripto
Content-Type: application/json

###

GET http://127.0.0.1:8000/tarjeta
Content-Type: application/json

###

GET http://127.0.0.1:8000/usd
Content-Type: application/json

###

GET http://127.0.0.1:8000/euro
Content-Type: application/json

###

GET http://127.0.0.1:8000/real
Content-Type: application/json

###

GET http://127.0.0.1:8000/clp
Content-Type: application/json

###

GET http://127.0.0.1:8000/uru
Content-Type: application/json

###

GET http://127.0.0.1:8000/cotizaciones
Content-Type: application/json

###

GET http://127.0.0.1:8000/oro
Content-Type: application/json

### API status

GET http://127.0.0.1:8000/
Content-Type: application/json

### docs:
### https://fastapiproject-1-eziw.onrender.com/docs
### https://fastapiproject-1-eziw.onrender.com/redoc

GET http://127.0.0.1:8000/convert/USD/EUR/100
Content-Type: application/json

###

GET http://127.0.0.1:8000/convert/UYU/USD/100
Content-Type: application/json

###

GET http://127.0.0.1:8000/convert/BTC/CNY/25000
Content-Type: application/json

###

GET http://127.0.0.1:8000/convert/JPY/BRL/100
Content-Type: application/json

###

GET http://127.0.0.1:8000/convert/AUD/USD/100
Content-Type: application/json

###